runtime: nodejs20
service: default

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  NODE_ENV: production
  API_BASE_URL: "https://backend.medsparsh.com"


