import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { AppBarWrapper } from "@/components/appbar-wrapper";
import { AuthProvider } from "@/components/AuthContext/AuthContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Platform Admin App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <AppBarWrapper />
          {children}</AuthProvider>
       
        
        <Toaster richColors position="top-center" toastOptions={{
          classNames: {
            toast: "bg-background border border-border text-foreground"
          }
        }} />
      </body>
    </html>
  );
}
